### ISSUE TITLE
composer name is `jambagecom/static-info-tables-es`

### ISSUE THREAD

**Issue by simonschaufi** [franzholz/static_info_tables_es#5]
Please fix this line: https://github.com/franzholz/static_info_tables_es/blob/master/composer.json#L2

**Comment by franzholz** [comment]
What do you mean? Give more details.

**Comment by simonschaufi** [comment]
There is no package with that name on https://packagist.org/search/?q=sjbr%2Fstatic-info-tables-es

The correct name is `jambagecom/static-info-tables-es` which should be reflected in the composer.json file

**Comment by franzholz** [comment]
Yes, however it seems that the vendor name sjbr must be used.
You can discuss this directly under static_info_tables.

**Comment by franzholz** [comment]
I get this information from packagist:

>  The vendor name "sjbr" was already claimed by someone else on Packagist.org. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at sjbr.If those packages belong to you but were submitted by someone else, you can contact us to resolve the issue.

**Comment by simonschaufi** [comment]
The vendor name doesn't need to match the composer name. There is no dependency but the composer name should match the one how the package is registered on packagist.

By the way, the sjbr is used by Stanislas Rolland. Talk to him if you want to move it to his namespace

**Comment by franzholz** [comment]
sjbr seems to be the company where Stanislas Rolland is working at the moment. So maybe it should not be used as a vendor name. 
I will wait for one week. Then you can send me a reminder if nothing happens. here.

**Comment by franzholz** [comment]
Stanislas Rolland has improved the extension static_info_tables last week.
#https://codeberg.org/sjbr/static-info-tables/commit/0b8c963c604ef817d906d5b655abeb7e4b44499b  

> In the case of static_info_tables_es, I think the vendor name "jambagecom" should be used in the name of the package that appears in the name parameter and the replace array of the composer.json configuration file.

**Comment by simonschaufi** [comment]
Great!
